# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: new-demo-jenkins
# spec:
#   selector:
#     matchLabels:
#       app: new-demo-jenkins
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: new-demo-jenkins
#     spec:
#       containers:
#       - name: new-demo-jenkins
#         image: rakshashenoy/keer:94
#         ports:
#         - containerPort: 9001


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: python-app-deployment
# spec:
#   replicas: 3  # Number of replicas (adjust as needed)
#   selector:
#     matchLabels:
#       app: python-app
#   template:
#     metadata:
#       labels:
#         app: python-app
#     spec:
#       containers:
#       - name: python-app
#         image: rakshashenoy/keer:82  # Replace with your Docker image name
#         ports:
#         - containerPort: 80  # Port your application listens on


apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-demo-jenkins
spec:
  selector:
    matchLabels:
      app: new-demo-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: new-demo-jenkins
    spec:
      containers:
      - name: new-demo-jenkins
        image: rakshashenoy/keer:94
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1  # Timeout for readiness probe
        livenessProbe:
          httpGet:
            path: /
            port: 9001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1  # Timeout for liveness probe
